out = paint_fibers(struct( ...
    'imageFile',  'colormap_fibers/T2_5.tif', ...
    'coordsXlsx', 'Line Scan Cords-2.xlsx', ...
    'matPath',    'matrix_to_paint_fibers.mat', ...
    'indexRange', [133 143], ...   % same subset as your script
    'squareSize', 50, ...
    'shape',      'square', ...    % or 'disk'
    'outDir',     'outputs', ...
    'savePrefix', 'T2_5', ...
    'verbose',    true ...
));
